<?php

namespace App\Models;

use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CareGiver extends Model
{
    use HasFactory;

    protected $guarded=[];
    protected $hidden = ['password'];

    protected $casts = [
        'dob' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::addGlobalScope(new ActiveScope());
    }

    public function appointments(){
        return $this->hasMany(CareGiverAppointment::class);
    }
}
