<?php

namespace App\Models;

use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class HomeSampleCategory extends Model
{
    use HasFactory;

    protected $guarded = [];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static :: addGlobalScope(new ActiveScope());
    }

    public function subcategories(){
        return $this->hasMany(HomeSampleSubcategory::class, 'home_sample_category_id');
    }
}
