<?php

namespace App\Models;

use App\Scopes\ActiveScope;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Therapist extends Model
{
    use HasFactory;

    protected $guarded = [];
    protected $hidden = ['password'];

    protected $casts = [
        'dob' => 'datetime',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static :: addGlobalScope(new ActiveScope());
    }

    public function location(){
        return $this->belongsTo(TherapistLocation::class, 'therapist_location_id');
    }

    public function appointments(){
        return $this->hasMany(TherapistAppointment::class, 'therapist_appointment_id');
    }
}
